// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: faas.proto

package faas_akt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Params struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JsonParamString string                 `protobuf:"bytes,1,opt,name=JsonParamString,proto3" json:"JsonParamString,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_faas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_faas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_faas_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetJsonParamString() string {
	if x != nil {
		return x.JsonParamString
	}
	return ""
}

type Result struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JsonResultString string                 `protobuf:"bytes,1,opt,name=JsonResultString,proto3" json:"JsonResultString,omitempty"`
	Logs             string                 `protobuf:"bytes,2,opt,name=Logs,proto3" json:"Logs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_faas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_faas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_faas_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetJsonResultString() string {
	if x != nil {
		return x.JsonResultString
	}
	return ""
}

func (x *Result) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_faas_proto protoreflect.FileDescriptor

const file_faas_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"faas.proto\x12\bfaas_akt\"2\n" +
	"\x06Params\x12(\n" +
	"\x0fJsonParamString\x18\x01 \x01(\tR\x0fJsonParamString\"H\n" +
	"\x06Result\x12*\n" +
	"\x10JsonResultString\x18\x01 \x01(\tR\x10JsonResultString\x12\x12\n" +
	"\x04Logs\x18\x02 \x01(\tR\x04Logs28\n" +
	"\x06Lambda\x12.\n" +
	"\x06Invoke\x12\x10.faas_akt.Params\x1a\x10.faas_akt.Result\"\x00B\x1cZ\x1agithub.com/Golos1/faas_aktb\x06proto3"

var (
	file_faas_proto_rawDescOnce sync.Once
	file_faas_proto_rawDescData []byte
)

func file_faas_proto_rawDescGZIP() []byte {
	file_faas_proto_rawDescOnce.Do(func() {
		file_faas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_faas_proto_rawDesc), len(file_faas_proto_rawDesc)))
	})
	return file_faas_proto_rawDescData
}

var file_faas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_faas_proto_goTypes = []any{
	(*Params)(nil), // 0: faas_akt.Params
	(*Result)(nil), // 1: faas_akt.Result
}
var file_faas_proto_depIdxs = []int32{
	0, // 0: faas_akt.Lambda.Invoke:input_type -> faas_akt.Params
	1, // 1: faas_akt.Lambda.Invoke:output_type -> faas_akt.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_faas_proto_init() }
func file_faas_proto_init() {
	if File_faas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_faas_proto_rawDesc), len(file_faas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faas_proto_goTypes,
		DependencyIndexes: file_faas_proto_depIdxs,
		MessageInfos:      file_faas_proto_msgTypes,
	}.Build()
	File_faas_proto = out.File
	file_faas_proto_goTypes = nil
	file_faas_proto_depIdxs = nil
}
