// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: faas.proto

package faas_akt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lambda_Invoke_FullMethodName = "/faas_akt.Lambda/Invoke"
)

// LambdaClient is the client API for Lambda service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LambdaClient interface {
	Invoke(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Result, error)
}

type lambdaClient struct {
	cc grpc.ClientConnInterface
}

func NewLambdaClient(cc grpc.ClientConnInterface) LambdaClient {
	return &lambdaClient{cc}
}

func (c *lambdaClient) Invoke(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Lambda_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LambdaServer is the server API for Lambda service.
// All implementations must embed UnimplementedLambdaServer
// for forward compatibility.
type LambdaServer interface {
	Invoke(context.Context, *Params) (*Result, error)
	mustEmbedUnimplementedLambdaServer()
}

// UnimplementedLambdaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLambdaServer struct{}

func (UnimplementedLambdaServer) Invoke(context.Context, *Params) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedLambdaServer) mustEmbedUnimplementedLambdaServer() {}
func (UnimplementedLambdaServer) testEmbeddedByValue()                {}

// UnsafeLambdaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LambdaServer will
// result in compilation errors.
type UnsafeLambdaServer interface {
	mustEmbedUnimplementedLambdaServer()
}

func RegisterLambdaServer(s grpc.ServiceRegistrar, srv LambdaServer) {
	// If the following call pancis, it indicates UnimplementedLambdaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lambda_ServiceDesc, srv)
}

func _Lambda_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lambda_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServer).Invoke(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

// Lambda_ServiceDesc is the grpc.ServiceDesc for Lambda service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lambda_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "faas_akt.Lambda",
	HandlerType: (*LambdaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Lambda_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faas.proto",
}
