name: Test
on: [push]

jobs:
  build_test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        name: get_credentials
        with:
          aws-region: 'us-east-2'
          role-to-assume: ${{secrets.AWS_ROLE}}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test Lambda
        run: |
          cd lambda
          go test
